# server port
server.port: 8081

spring:
  # set the active profile
  profiles:
    active: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: false
  # access console http://localhost:8081/h2-console
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:testdb

# spring boot actuator configuration

# enable all endpoints
management.endpoints.web.exposure.include: "*"
management.endpoints.jmx.exposure.include: "*"

# disable endpoints
management.endpoints.web.exposure.exclude: health,info,env,beans
management.endpoints.jmx.exposure.exclude: health,info,env,beans
