appOwner: company
releaseVersion: 1.0

# starter-web or jpa is using logback with slf4j as implementation
logging:
  # default logging goes to console
  file: spring-boot/log/app.log # write logs to this file
  level:
    root: INFO
    org.springframework: ERROR
    com.sda.spring.boot: INFO
